name: langflow

services:
  langflow:
    image: langflowai/langflow:1.3.4
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - redis
      - qdrant
    environment:
      # Postgres for Langflow database
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # Redis for chat memory
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      # Qdrant for vector storage
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import socket; s=socket.socket(); s.connect(('localhost', 7860)) or exit(0); s.close()\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - langflow-redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.14.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - langflow-qdrant:/qdrant/storage

volumes:
  langflow-postgres:
    name: langflow-postgres
  langflow-redis:
    name: langflow-redis
  langflow-qdrant:
    name: langflow-qdrant
